# Generated by Django 2.1.1 on 2018-11-07 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='serie',
            table='series',
        ),
    ]
